---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    journald_enable_remote_logging: >-
      {{ ansible_facts['service_mgr'] == 'systemd' and ansible_facts['os_family'] == 'RedHat' }}
    journald_manage_tmpfiles_permissions: true
    journald_tmpfiles_file_mode: "0640"
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
